# Makefile

VERILOG_SOURCES = $(PWD)/path/to/your/RISC_V_RV32I_Skeleton.v
TOPLEVEL = RISC_V_RV32I
MODULE = alu_tb
SIM = verilator

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim

